baseURL: http://example.org/
languageCode: en-us
title: "My New Hugo Site"
theme: "toha"

languages:
    en:
        languageName: English
        weight: 1

markup:
    tableOfContents:
        startLevel: 2
        endLevel: 6
        ordered: false

outputs:
    home:
    - HTML
    - JSON

enableEmoji: true


