baseURL: http://bretbeatty.me/
languageCode: en-us
title: "Bret Beatty"
theme: "toha"

minify:
    disableHTML: true

languages:
    en:
        languageName: English
        weight: 1

markup:
    tableOfContents:
        startLevel: 1
        endLevel: 6
        ordered: false

outputs:
    home:
    - HTML
    - JSON

enableEmoji: true

params:
    # gitRepo: https://github.com/bab014/bretbeatty
    # gitBranch: master
    background: "images/default-background.jpg"
    enableBlogPost: true
    enableTOC: true
    newsletter:
        enable: false
    features:
        blog:
            enable: true
    # logo:
    #     main: images/bret-logo.png
    #     inverted: images/bret-logo.png

